### PR TITLE
pnpm i -f must be ran after a build, when using depMea.*.injected

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
due to https://github.com/CrowdStrike/ember-headless-form/pull/49#issuecomment-1431309759, 
https://github.com/CrowdStrike/ember-headless-form/pull/45 is no longer viable.

See: https://github.com/pnpm/pnpm/issues/6088

### CODE REVIEW

**Review by ynotdraw — APPROVED** [review]

**Review by simonihmig — APPROVED** [review]

**Comment by simonihmig** [comment]
Ok, I could have done that as part of #49. But I thought we would be able to land #45...

This is not feasible currently, as the build step triggered by turbo would need to _also_ have `pnpm i -f`. But still theoretically we could do this? It is just too costly here? More costly than what we have with this PR?

**Comment by NullVoxPopuli** [comment]
> But still theoretically we could do this?

I don't think it's possible -- I opened an issue with turbo here: https://github.com/vercel/turbo/issues/2306 and we tried some solutions, but ultimately, we need to solve: https://github.com/pnpm/pnpm/issues/6088

**Comment by simonihmig** [comment]
Maybe I am misunderstanding this, but couldn't we just modify the `build` script to be something like `"build": "rollup --config && pnpm i -f",`? We are basically doing this here, only at the CI workflow level. Not saying this is nice, but would it work?

**Comment by NullVoxPopuli** [comment]
on a cache-hit, the entirety of the `build` script would be skipped, and the links in `node_modules/.pnpm` not updated

**Comment by simonihmig** [comment]
Oh, right. This was the missing bit 😔

**Pull request merged**
